core/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from .views import GenerateRandomUserForm
from .views import UsersListView

urlpatterns = [
    url(r'templates/$', GenerateRandomUserForm.as_view(), name='GenerateRandomUserForm'),
    url(r'users/$', UsersListView.as_view(), name='userlist'),
]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^core/', include('core.urls', namespace='core'))
]

core/models.py
from django.db import models

# Create your models here.

core/forms.py
from django import forms
from django.core.validators import MinValueValidator, MaxValueValidator

class GenerateRandomUserForm(forms.Form):
	total = forms.IntegerField (
		validators = [
			MinValueValidator (50),
			MaxValueValidator(500)
		]
	)

core/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from django.contrib import messages
from django.views.generic.edit import FormView
from django.shortcuts import redirect
from django.views import generic

from .forms import GenerateRandomUserForm
from .tasks import create_random_user_accounts
  
class  GenerateRandomUserForm(FormView):
        template_name = 'generate_random_users.html'
        form_class = GenerateRandomUserForm

def form_valid(self, form):
    total = form.cleaned_data.get('total')                                                                                            
    create_random_user_accounts.delay(total)
    messages.success(self.request, 'We are generating your random users! Wait a moment and refresh this page.')
    return redirect('users_list')

class  UsersListView(generic.ListView):
     template_name = 'users/generate_random_users.html'
     model = User

def get_queryset(self):
    return User.objects.all()

core/templates/generate_random_users.html
<html>
    <head>
        <title>Django Celery Example</title>
        {% load bootstrap3 %}
        {% bootstrap_css %}
        {% bootstrap_javascript %}
<h1>Django Celery Example</h1>

<a href="{% url 'core:userlist' %}">User List</a>
<a href="{% url 'core:GenerateRandomUserForm' %}">Random User</a>


<form>
    {{ form.as_p }}
    <input type="submit" value="Total" />
</form>
	<body>
	{% block content%}

	{%endblock%}

	</body>
	
</head>